### ISSUE TITLE
Search Bar in Student Page

### ISSUE THREAD

**Issue by sophiacrennan** [sandboxnu/pharmd-tracker#45]
**Problem**: The search bar on the student page is not working
**Solution**: Should be able to search by student's many columns

**Description**: #36 is displaying all existing students on the student page (part of connecting frontend and backend). Ran into the issue where the search bar no longer works. We want to be able to search by a student's many columns.

**Specs:**
- [x] can search by NUID
- [x] can search by firstName
- [x] can search by lastName
- [ ] can search by Cohort
- [ ] can search by Status
- [ ] can search by GPA
- [x] search does not have to be an exact match (can start with or contain value) 

**Where to start**:
Compare the functionality of searching in the `master` branch and in the `connect-to-backend` branch. Branch off of `connect-to-backend` to write the solution. The Student Page files are in `/pharmd-tracker/pharmd-app/src/screens/student/`. 

If blocked, contact @sophiacrennan

**Comment by VKong6019** [comment]
seems like sorting also doesn't work and is similar to the search/sort issues with courses, so i'll also work on adding the sort functionality in my pr
